<?php

namespace App\Http\Controllers\hclinico;

use App\Http\Controllers\Controller;
use App\Http\Resources\RespuestaApi;
use App\Models\Paciente;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FormPeriodico extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:api', ['except' => [
            'byIdentificacion', 'edit'
        ]]);
    }

    public function store($identificacion, $pacId)
    {
        try {

            $paciente = Paciente::where('pac_identificacion', $identificacion)->first();
            $ocupacional = DB::selectOne("SELECT
                c_anteceden_clinicos_quirur,
                c_cons_otra_droga,
                c_tiempo_cons_otras,
                c_cantidad_cons_otras,
                c_ex_cons_otras,
                c_cons_otra_droga2,
                c_tiempo_cons_otras2,
                c_cantidad_cons_otras2,
                c_ex_cons_otras2,
                c_tiempo_cons_tabaco,
                c_cantidad_cons_tabaco,
                c_tiem_absti_tabaco,
                c_cantidad_cons_alcohol,
                c_tiempo_cons_alcohol,
                c_tiem_abst_alcohol,
                c_ex_cons_tabaco,
                c_cons_alcohol,
                c_ex_cons_alcohol,
                c_cons_otras,
                c_activi_fisica
                c_desc_actifisica,
                c_tiemp_actifisica,
                c_medicacion_habitual,
                c_medicacion_habitual1,
                c_tiem_medicacion_habitual1,
                c_medicacion_habitual2,
                c_tiem_medicacion_habitual2,
                c_medicacion_habitual3,
                c_tiem_medicacion_habitual3,
                d_calificado_sri_acci
                d_especificar_acci,
                d_fecha_acci,
                d_acci_trabajo_dec,
                d_calificado_sri_ep,
                d_especificar_ep,
                d_fecha_ep,
                d_enfe_profesi_dec,
                e_desc_cardiovascular
                e_desc_metabolica,
                e_desc_neurologica,
                e_desc_oncologica,
                e_desc_infecciosa,
                e_desc_hereditaria_congenita,
                e_desc_discapacidades,
                e_desc_otra,
                f_temperaturas_altas1,
                f_temperaturas_bajas1,
                f_radiacion_ionizante1,
                f_radiacion_no_ionizante1,
                f_ruido1,
                f_vibracion1,
                f_iluminacion1,
                f_ventilacion1,
                f_fluido_electrico1,
                f_fisico_otro1,
                f_fisico_otro_desc1,
                f_atrapa_entre_maquinas1,
                f_atrapa_entre_superficies1,
                f_atrapa_entre_objetos1,
                f_caida_objetos1,
                f_aidas_mismo_nivel1,
                f_caidas_diferente_nivel1,
                f_contacto_electrico1,
                f_contacto_superf_trabajos1,
                f_proye_particulas_fragm1,
                f_proye_fluidos1,
                f_pinchazos1,
                f_cortes1,
                f_tropellamientos_vehiculos1,
                f_choques_colision_vehicular1,
                f_mecanico_otro1,
                f_mecanico_otro_desc1,
                f_solidos1,
                f_polvos1,
                f_humos1,
                f_liquidos1,
                f_vapoores1,
                f_aerosoles1,
                f_neblinas1,
                f_gaseosos1,
                f_quimico_otros1,
                f_quimico_otros_desc1,
                f_virus1,
                f_hongos1,
                f_bacterias1,
                f_parasitos1,
                f_expo_factores1,
                f_expo_animselvaticos1,
                f_biologico_otro1,
                f_biologico_otro_desc1,
                f_manejo_manual_cargas1,
                f_movimie_repetitivos1,
                f_posturas_forzadas1,
                f_trabajos_pvd1,
                f_ergonomico_otro1,
                f_ergonomico_otro_desc1,
                f_monot_trabajo1,
                f_sobrec_laboral1,
                f_minuci_tarea1,
                f_alta_responsa1,
                f_toma_decisiones1,
                f_sed_deficiente1,
                f_conflicto_rol1,
                f_alta_claridad_funcio1,
                f_inco_distrib_trabajo1,
                f_turnos_rotativos1,
                f_relacio_interp1,
                f_inesta_laboral1,
                f_psicosocial_otro1,
                f_psicosocial_otro_desc1,
                f_puestotrabajo1,
                f_actividad1,
                f_medidas_preventivas1,
                f_temperaturas_altas2,
                f_temperaturas_bajas2,
                f_radiacion_ionizante2,
                f_radiacion_no_ionizante2,
                f_ruido2,
                f_vibracion2,
                f_iluminacion2,
                f_ventilacion2,
                f_fluido_electrico2,
                f_fisico_otro2,
                f_fisico_otro_desc2,
                f_atrapa_entre_maquinas2,
                f_atrapa_entre_superficies2,
                f_atrapa_entre_objetos2,
                f_caida_objetos2,
                f_aidas_mismo_nivel2,
                f_caidas_diferente_nivel2,
                f_contacto_electrico2,
                f_contacto_superf_trabajos2,
                f_proye_particulas_fragm2,
                f_proye_fluidos2,
                f_pinchazos2,
                f_cortes2,
                f_tropellamientos_vehiculos2,
                f_choques_colision_vehicular2,
                f_mecanico_otro2,
                f_mecanico_otro_desc2,
                f_solidos2,
                f_polvos2,
                f_humos2,
                f_liquidos2,
                f_vapoores2,
                f_aerosoles2,
                f_neblinas2,
                f_gaseosos2,
                f_quimico_otros2,
                f_quimico_otros_desc2,
                f_virus2,
                f_hongos2,
                f_bacterias2,
                f_parasitos2,
                f_expo_factores2,
                f_expo_animselvaticos2,
                f_biologico_otro2,
                f_biologico_otro_desc2,
                f_manejo_manual_cargas2,
                f_movimie_repetitivos2,
                f_posturas_forzadas2,
                f_trabajos_pvd2,
                f_ergonomico_otro2,
                f_ergonomico_otro_desc2,
                f_monot_trabajo2,
                f_sobrec_laboral2,
                f_minuci_tarea2,
                f_alta_responsa2,
                f_toma_decisiones2,
                f_sed_deficiente2,
                f_conflicto_rol2,
                f_alta_claridad_funcio2,
                f_inco_distrib_trabajo2,
                f_turnos_rotativos2,
                f_relacio_interp2,
                f_inesta_laboral2,
                f_psicosocial_otro2,
                f_psicosocial_otro_desc2,
                f_puestotrabajo2,
                f_actividad2,
                f_medidas_preventivas2
                from hclinico.formulario_ocupacional fo where fo.pac_id = $pacId");

            $data = (object)[
                "paciente" => $paciente,
                "ocupacional" => $ocupacional,
            ];


            return response()->json(RespuestaApi::returnResultado('success', 'Listado con éxito.', $data));
        } catch (\Throwable $th) {
            return response()->json(RespuestaApi::returnResultado('error', 'Error al listar.', $th->getMessage()));
        }
    }
}
