INSERT INTO public.dmenu
(cme_id, dme_texto, dme_seguridad, prg_id, dme_orden, dme_activo, cme_padre, "locked", dme_preciador)
VALUES(220, 'CXC', '0', NULL, 1, false, 385, false, false);
INSERT INTO public.dmenu
(cme_id, dme_texto, dme_seguridad, prg_id, dme_orden, dme_activo, cme_padre, "locked", dme_preciador)
VALUES(222, 'COMERCIALIZACION', '0', NULL, 2, false, 385, false, false);
INSERT INTO public.dmenu
(cme_id, dme_texto, dme_seguridad, prg_id, dme_orden, dme_activo, cme_padre, "locked", dme_preciador)
VALUES(217, 'CAJAS', '0', NULL, 3, true, 385, false, false);
INSERT INTO public.dmenu
(cme_id, dme_texto, dme_seguridad, prg_id, dme_orden, dme_activo, cme_padre, "locked", dme_preciador)
VALUES(234, 'INVENTARIOS', '0', NULL, 0, false, 385, false, false);
INSERT INTO public.dmenu
(cme_id, dme_texto, dme_seguridad, prg_id, dme_orden, dme_activo, cme_padre, "locked", dme_preciador)
VALUES(290, 'NOCHE DE LOCURA', '0', NULL, 4, false, 385, false, false);
INSERT INTO public.dmenu
(cme_id, dme_texto, dme_seguridad, prg_id, dme_orden, dme_activo, cme_padre, "locked", dme_preciador)
VALUES(372, 'QR PRECIADOR', '0', NULL, 5, true, 385, false, NULL);
