#Configuración para pantalla: CP_config.properties
#Tue Apr 28 13:00:48 ECT 2026
gatewayField=192.168.1.200
tcpPortHost1Field=
ipHost2Field=
ipAltHost1Field=
maskField=255.255.255.0
ipField=192.168.1.242
tcpPortAltHost2Field=
listeningPortField=6500
tcpPortHost2Field=
ipAltHost2Field=
ipHost1Field=
tcpPortAltHost1Field=
